name: Build and Publish Daily

on:
  schedule:
    # roda todo dia às 06:00 UTC (03:00 São Paulo)
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: |
          npm install

      - name: Build site (gera novo post e atualiza /public)
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          npm run build-site

      - name: Publish to gh-pages
        run: |
            # limpa qualquer worktree residual
            git worktree prune
            rm -rf deploy

            # busca branch gh-pages (se existir)
            git fetch origin gh-pages || true

            # deleta branch local se existir (evita conflito)
            git branch -D gh-pages || true

            # cria um worktree limpo
            git worktree add deploy gh-pages || git worktree add deploy -b gh-pages

            # limpa conteúdo anterior e copia o novo
            rm -rf deploy/*
            cp -r public/* deploy/

            cd deploy
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "publish: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "nada pra commitar"
            git push origin gh-pages
