name: Build and Publish Daily

on:
  schedule:
    - cron: "0 6 * * *"  # todo dia às 06:00 UTC
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: |
          npm install

      - name: Build site (gera novo post e atualiza /public)
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          npm run build-site

      # A partir daqui, a gente faz o publish manualmente sem worktree
      - name: Deploy to gh-pages
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            # configura git para commit automatizado
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"

            # se ainda não existe branch gh-pages no remoto, cria
            if ! git ls-remote --exit-code origin gh-pages; then
            echo "gh-pages não existe ainda, criando..."
            git checkout --orphan gh-pages
            git rm -rf .
            echo "<html><body>init</body></html>" > index.html
            git add index.html
            git commit -m "init gh-pages"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/TGalter/autopost-site.git gh-pages
            git checkout main
            fi

            # cria pasta limpa de deploy
            rm -rf deploy
            mkdir deploy
            cp -r public/* deploy/

            cd deploy
            git init
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git checkout -b gh-pages
            git add .
            git commit -m "publish: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"

            # push forçado pro branch gh-pages usando token
            git push --force https://x-access-token:${GITHUB_TOKEN}@github.com/TGalter/autopost-site.git gh-pages
